//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SimpleMapDemo.RWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddMemberShortOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateLoginDateTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeInfoShortOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddRecyclingOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckRecyclingOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetRecyclingTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelPersonRecyclingOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeDriverOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTicketOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = "http://138.201.96.143/web/Service.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddMemberCompletedEventHandler AddMemberCompleted;
        
        /// <remarks/>
        public event GetInfoCompletedEventHandler GetInfoCompleted;
        
        /// <remarks/>
        public event AddMemberShortCompletedEventHandler AddMemberShortCompleted;
        
        /// <remarks/>
        public event UpdateLoginDateTimeCompletedEventHandler UpdateLoginDateTimeCompleted;
        
        /// <remarks/>
        public event ChangeInfoCompletedEventHandler ChangeInfoCompleted;
        
        /// <remarks/>
        public event ChangeInfoShortCompletedEventHandler ChangeInfoShortCompleted;
        
        /// <remarks/>
        public event CheckMemberCompletedEventHandler CheckMemberCompleted;
        
        /// <remarks/>
        public event DeleteMemberCompletedEventHandler DeleteMemberCompleted;
        
        /// <remarks/>
        public event AddRecyclingCompletedEventHandler AddRecyclingCompleted;
        
        /// <remarks/>
        public event CheckRecyclingCompletedEventHandler CheckRecyclingCompleted;
        
        /// <remarks/>
        public event SetRecyclingTypeCompletedEventHandler SetRecyclingTypeCompleted;
        
        /// <remarks/>
        public event CancelPersonRecyclingCompletedEventHandler CancelPersonRecyclingCompleted;
        
        /// <remarks/>
        public event ChangeStatusCompletedEventHandler ChangeStatusCompleted;
        
        /// <remarks/>
        public event ChangeDriverCompletedEventHandler ChangeDriverCompleted;
        
        /// <remarks/>
        public event SendTicketCompletedEventHandler SendTicketCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddMember", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddMember(string address, System.DateTime birthday, string email, bool gender, string firstName, string lastName, string nationalCode, string phone, string referalCode, System.DateTime registerDate) {
            object[] results = this.Invoke("AddMember", new object[] {
                        address,
                        birthday,
                        email,
                        gender,
                        firstName,
                        lastName,
                        nationalCode,
                        phone,
                        referalCode,
                        registerDate});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddMemberAsync(string address, System.DateTime birthday, string email, bool gender, string firstName, string lastName, string nationalCode, string phone, string referalCode, System.DateTime registerDate) {
            this.AddMemberAsync(address, birthday, email, gender, firstName, lastName, nationalCode, phone, referalCode, registerDate, null);
        }
        
        /// <remarks/>
        public void AddMemberAsync(string address, System.DateTime birthday, string email, bool gender, string firstName, string lastName, string nationalCode, string phone, string referalCode, System.DateTime registerDate, object userState) {
            if ((this.AddMemberOperationCompleted == null)) {
                this.AddMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddMemberOperationCompleted);
            }
            this.InvokeAsync("AddMember", new object[] {
                        address,
                        birthday,
                        email,
                        gender,
                        firstName,
                        lastName,
                        nationalCode,
                        phone,
                        referalCode,
                        registerDate}, this.AddMemberOperationCompleted, userState);
        }
        
        private void OnAddMemberOperationCompleted(object arg) {
            if ((this.AddMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddMemberCompleted(this, new AddMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetInfo(string phoneNumber) {
            object[] results = this.Invoke("GetInfo", new object[] {
                        phoneNumber});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoAsync(string phoneNumber) {
            this.GetInfoAsync(phoneNumber, null);
        }
        
        /// <remarks/>
        public void GetInfoAsync(string phoneNumber, object userState) {
            if ((this.GetInfoOperationCompleted == null)) {
                this.GetInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoOperationCompleted);
            }
            this.InvokeAsync("GetInfo", new object[] {
                        phoneNumber}, this.GetInfoOperationCompleted, userState);
        }
        
        private void OnGetInfoOperationCompleted(object arg) {
            if ((this.GetInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoCompleted(this, new GetInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddMemberShort", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddMemberShort(string phone, System.DateTime registerDate) {
            object[] results = this.Invoke("AddMemberShort", new object[] {
                        phone,
                        registerDate});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddMemberShortAsync(string phone, System.DateTime registerDate) {
            this.AddMemberShortAsync(phone, registerDate, null);
        }
        
        /// <remarks/>
        public void AddMemberShortAsync(string phone, System.DateTime registerDate, object userState) {
            if ((this.AddMemberShortOperationCompleted == null)) {
                this.AddMemberShortOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddMemberShortOperationCompleted);
            }
            this.InvokeAsync("AddMemberShort", new object[] {
                        phone,
                        registerDate}, this.AddMemberShortOperationCompleted, userState);
        }
        
        private void OnAddMemberShortOperationCompleted(object arg) {
            if ((this.AddMemberShortCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddMemberShortCompleted(this, new AddMemberShortCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateLoginDateTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateLoginDateTime(string phoneNumber) {
            object[] results = this.Invoke("UpdateLoginDateTime", new object[] {
                        phoneNumber});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateLoginDateTimeAsync(string phoneNumber) {
            this.UpdateLoginDateTimeAsync(phoneNumber, null);
        }
        
        /// <remarks/>
        public void UpdateLoginDateTimeAsync(string phoneNumber, object userState) {
            if ((this.UpdateLoginDateTimeOperationCompleted == null)) {
                this.UpdateLoginDateTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateLoginDateTimeOperationCompleted);
            }
            this.InvokeAsync("UpdateLoginDateTime", new object[] {
                        phoneNumber}, this.UpdateLoginDateTimeOperationCompleted, userState);
        }
        
        private void OnUpdateLoginDateTimeOperationCompleted(object arg) {
            if ((this.UpdateLoginDateTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateLoginDateTimeCompleted(this, new UpdateLoginDateTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangeInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChangeInfo(string address, System.DateTime birthday, string email, bool gender, string firstName, string lastName, string nationalCode, string phone, string referalCode, System.DateTime registerDate) {
            object[] results = this.Invoke("ChangeInfo", new object[] {
                        address,
                        birthday,
                        email,
                        gender,
                        firstName,
                        lastName,
                        nationalCode,
                        phone,
                        referalCode,
                        registerDate});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeInfoAsync(string address, System.DateTime birthday, string email, bool gender, string firstName, string lastName, string nationalCode, string phone, string referalCode, System.DateTime registerDate) {
            this.ChangeInfoAsync(address, birthday, email, gender, firstName, lastName, nationalCode, phone, referalCode, registerDate, null);
        }
        
        /// <remarks/>
        public void ChangeInfoAsync(string address, System.DateTime birthday, string email, bool gender, string firstName, string lastName, string nationalCode, string phone, string referalCode, System.DateTime registerDate, object userState) {
            if ((this.ChangeInfoOperationCompleted == null)) {
                this.ChangeInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeInfoOperationCompleted);
            }
            this.InvokeAsync("ChangeInfo", new object[] {
                        address,
                        birthday,
                        email,
                        gender,
                        firstName,
                        lastName,
                        nationalCode,
                        phone,
                        referalCode,
                        registerDate}, this.ChangeInfoOperationCompleted, userState);
        }
        
        private void OnChangeInfoOperationCompleted(object arg) {
            if ((this.ChangeInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeInfoCompleted(this, new ChangeInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangeInfoShort", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChangeInfoShort(string address, string email, bool gender, string firstName, string lastName, string nationalCode, string phone, string referalCode) {
            object[] results = this.Invoke("ChangeInfoShort", new object[] {
                        address,
                        email,
                        gender,
                        firstName,
                        lastName,
                        nationalCode,
                        phone,
                        referalCode});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeInfoShortAsync(string address, string email, bool gender, string firstName, string lastName, string nationalCode, string phone, string referalCode) {
            this.ChangeInfoShortAsync(address, email, gender, firstName, lastName, nationalCode, phone, referalCode, null);
        }
        
        /// <remarks/>
        public void ChangeInfoShortAsync(string address, string email, bool gender, string firstName, string lastName, string nationalCode, string phone, string referalCode, object userState) {
            if ((this.ChangeInfoShortOperationCompleted == null)) {
                this.ChangeInfoShortOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeInfoShortOperationCompleted);
            }
            this.InvokeAsync("ChangeInfoShort", new object[] {
                        address,
                        email,
                        gender,
                        firstName,
                        lastName,
                        nationalCode,
                        phone,
                        referalCode}, this.ChangeInfoShortOperationCompleted, userState);
        }
        
        private void OnChangeInfoShortOperationCompleted(object arg) {
            if ((this.ChangeInfoShortCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeInfoShortCompleted(this, new ChangeInfoShortCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckMember", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckMember(string phone) {
            object[] results = this.Invoke("CheckMember", new object[] {
                        phone});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckMemberAsync(string phone) {
            this.CheckMemberAsync(phone, null);
        }
        
        /// <remarks/>
        public void CheckMemberAsync(string phone, object userState) {
            if ((this.CheckMemberOperationCompleted == null)) {
                this.CheckMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckMemberOperationCompleted);
            }
            this.InvokeAsync("CheckMember", new object[] {
                        phone}, this.CheckMemberOperationCompleted, userState);
        }
        
        private void OnCheckMemberOperationCompleted(object arg) {
            if ((this.CheckMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckMemberCompleted(this, new CheckMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteMember", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteMember(string phone) {
            object[] results = this.Invoke("DeleteMember", new object[] {
                        phone});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMemberAsync(string phone) {
            this.DeleteMemberAsync(phone, null);
        }
        
        /// <remarks/>
        public void DeleteMemberAsync(string phone, object userState) {
            if ((this.DeleteMemberOperationCompleted == null)) {
                this.DeleteMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMemberOperationCompleted);
            }
            this.InvokeAsync("DeleteMember", new object[] {
                        phone}, this.DeleteMemberOperationCompleted, userState);
        }
        
        private void OnDeleteMemberOperationCompleted(object arg) {
            if ((this.DeleteMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMemberCompleted(this, new DeleteMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddRecycling", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddRecycling(string phone, string location_X, string location_Y, int status, System.DateTime submitDate, int type, double weight) {
            object[] results = this.Invoke("AddRecycling", new object[] {
                        phone,
                        location_X,
                        location_Y,
                        status,
                        submitDate,
                        type,
                        weight});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddRecyclingAsync(string phone, string location_X, string location_Y, int status, System.DateTime submitDate, int type, double weight) {
            this.AddRecyclingAsync(phone, location_X, location_Y, status, submitDate, type, weight, null);
        }
        
        /// <remarks/>
        public void AddRecyclingAsync(string phone, string location_X, string location_Y, int status, System.DateTime submitDate, int type, double weight, object userState) {
            if ((this.AddRecyclingOperationCompleted == null)) {
                this.AddRecyclingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddRecyclingOperationCompleted);
            }
            this.InvokeAsync("AddRecycling", new object[] {
                        phone,
                        location_X,
                        location_Y,
                        status,
                        submitDate,
                        type,
                        weight}, this.AddRecyclingOperationCompleted, userState);
        }
        
        private void OnAddRecyclingOperationCompleted(object arg) {
            if ((this.AddRecyclingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddRecyclingCompleted(this, new AddRecyclingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckRecycling", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckRecycling(string phone) {
            object[] results = this.Invoke("CheckRecycling", new object[] {
                        phone});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckRecyclingAsync(string phone) {
            this.CheckRecyclingAsync(phone, null);
        }
        
        /// <remarks/>
        public void CheckRecyclingAsync(string phone, object userState) {
            if ((this.CheckRecyclingOperationCompleted == null)) {
                this.CheckRecyclingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckRecyclingOperationCompleted);
            }
            this.InvokeAsync("CheckRecycling", new object[] {
                        phone}, this.CheckRecyclingOperationCompleted, userState);
        }
        
        private void OnCheckRecyclingOperationCompleted(object arg) {
            if ((this.CheckRecyclingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckRecyclingCompleted(this, new CheckRecyclingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetRecyclingType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SetRecyclingType(bool Type1, bool Type2, bool Type3, bool Type4, bool Type5) {
            object[] results = this.Invoke("SetRecyclingType", new object[] {
                        Type1,
                        Type2,
                        Type3,
                        Type4,
                        Type5});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SetRecyclingTypeAsync(bool Type1, bool Type2, bool Type3, bool Type4, bool Type5) {
            this.SetRecyclingTypeAsync(Type1, Type2, Type3, Type4, Type5, null);
        }
        
        /// <remarks/>
        public void SetRecyclingTypeAsync(bool Type1, bool Type2, bool Type3, bool Type4, bool Type5, object userState) {
            if ((this.SetRecyclingTypeOperationCompleted == null)) {
                this.SetRecyclingTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetRecyclingTypeOperationCompleted);
            }
            this.InvokeAsync("SetRecyclingType", new object[] {
                        Type1,
                        Type2,
                        Type3,
                        Type4,
                        Type5}, this.SetRecyclingTypeOperationCompleted, userState);
        }
        
        private void OnSetRecyclingTypeOperationCompleted(object arg) {
            if ((this.SetRecyclingTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetRecyclingTypeCompleted(this, new SetRecyclingTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelPersonRecycling", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CancelPersonRecycling(string phoneNumber) {
            object[] results = this.Invoke("CancelPersonRecycling", new object[] {
                        phoneNumber});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CancelPersonRecyclingAsync(string phoneNumber) {
            this.CancelPersonRecyclingAsync(phoneNumber, null);
        }
        
        /// <remarks/>
        public void CancelPersonRecyclingAsync(string phoneNumber, object userState) {
            if ((this.CancelPersonRecyclingOperationCompleted == null)) {
                this.CancelPersonRecyclingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelPersonRecyclingOperationCompleted);
            }
            this.InvokeAsync("CancelPersonRecycling", new object[] {
                        phoneNumber}, this.CancelPersonRecyclingOperationCompleted, userState);
        }
        
        private void OnCancelPersonRecyclingOperationCompleted(object arg) {
            if ((this.CancelPersonRecyclingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelPersonRecyclingCompleted(this, new CancelPersonRecyclingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangeStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChangeStatus(string phone, int status) {
            object[] results = this.Invoke("ChangeStatus", new object[] {
                        phone,
                        status});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeStatusAsync(string phone, int status) {
            this.ChangeStatusAsync(phone, status, null);
        }
        
        /// <remarks/>
        public void ChangeStatusAsync(string phone, int status, object userState) {
            if ((this.ChangeStatusOperationCompleted == null)) {
                this.ChangeStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeStatusOperationCompleted);
            }
            this.InvokeAsync("ChangeStatus", new object[] {
                        phone,
                        status}, this.ChangeStatusOperationCompleted, userState);
        }
        
        private void OnChangeStatusOperationCompleted(object arg) {
            if ((this.ChangeStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeStatusCompleted(this, new ChangeStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangeDriver", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChangeDriver(string phone, int driverId) {
            object[] results = this.Invoke("ChangeDriver", new object[] {
                        phone,
                        driverId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeDriverAsync(string phone, int driverId) {
            this.ChangeDriverAsync(phone, driverId, null);
        }
        
        /// <remarks/>
        public void ChangeDriverAsync(string phone, int driverId, object userState) {
            if ((this.ChangeDriverOperationCompleted == null)) {
                this.ChangeDriverOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeDriverOperationCompleted);
            }
            this.InvokeAsync("ChangeDriver", new object[] {
                        phone,
                        driverId}, this.ChangeDriverOperationCompleted, userState);
        }
        
        private void OnChangeDriverOperationCompleted(object arg) {
            if ((this.ChangeDriverCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeDriverCompleted(this, new ChangeDriverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendTicket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendTicket(string phone, string ticketMessege) {
            object[] results = this.Invoke("SendTicket", new object[] {
                        phone,
                        ticketMessege});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendTicketAsync(string phone, string ticketMessege) {
            this.SendTicketAsync(phone, ticketMessege, null);
        }
        
        /// <remarks/>
        public void SendTicketAsync(string phone, string ticketMessege, object userState) {
            if ((this.SendTicketOperationCompleted == null)) {
                this.SendTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTicketOperationCompleted);
            }
            this.InvokeAsync("SendTicket", new object[] {
                        phone,
                        ticketMessege}, this.SendTicketOperationCompleted, userState);
        }
        
        private void OnSendTicketOperationCompleted(object arg) {
            if ((this.SendTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTicketCompleted(this, new SendTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void AddMemberCompletedEventHandler(object sender, AddMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetInfoCompletedEventHandler(object sender, GetInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void AddMemberShortCompletedEventHandler(object sender, AddMemberShortCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddMemberShortCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddMemberShortCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void UpdateLoginDateTimeCompletedEventHandler(object sender, UpdateLoginDateTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateLoginDateTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateLoginDateTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ChangeInfoCompletedEventHandler(object sender, ChangeInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ChangeInfoShortCompletedEventHandler(object sender, ChangeInfoShortCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeInfoShortCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeInfoShortCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void CheckMemberCompletedEventHandler(object sender, CheckMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void DeleteMemberCompletedEventHandler(object sender, DeleteMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void AddRecyclingCompletedEventHandler(object sender, AddRecyclingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddRecyclingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddRecyclingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void CheckRecyclingCompletedEventHandler(object sender, CheckRecyclingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckRecyclingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckRecyclingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SetRecyclingTypeCompletedEventHandler(object sender, SetRecyclingTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetRecyclingTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetRecyclingTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void CancelPersonRecyclingCompletedEventHandler(object sender, CancelPersonRecyclingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelPersonRecyclingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelPersonRecyclingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ChangeStatusCompletedEventHandler(object sender, ChangeStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ChangeDriverCompletedEventHandler(object sender, ChangeDriverCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeDriverCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeDriverCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SendTicketCompletedEventHandler(object sender, SendTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591